[project]
name = "pyvicp"
description = "LeCroy VICP protocol in pure Python"
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name="Anthony Cake" },
  { name="Urs Schroffenegger" },
  { name="Bob McNamara" },
]
maintainers = [
  { name="Bob McNamara", email="bobm.vegan@gmail.com" },
]
keywords = [
    "VICP",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Programming Language :: Python",
    "Topic :: Scientific/Engineering :: Interface Engine/Protocol Translator",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "importlib-metadata; python_version<'3.8'",
]
dynamic=["version"]

[project.urls]
"Homepage" = "https://github.com/bobmcnamara/pyvicp"
"Bug Tracker" = "https://github.com/bobmcnamara/pyvicp/issues"

[build-system]
requires = ["setuptools>=61.2", "wheel", "setuptools_scm[toml]>=3.4.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "pyvicp/version.py"
write_to_template = """
# This file is auto-generated by setuptools-scm do NOT edit it.
__version__ = "{version}"
"""


[tool.pytest.ini_options]
minversion = "6.0"

[tool.mypy]
follow_imports = "normal"
strict_optional = true

ignore_missing_imports = true

[tool.isort]
profile = "black"
combine_as_imports = true
